In [30]:
import pandas as pd

In [31]:
data = {"x1": [i for i in range(5)], "x2": [i for i in range(10,15)], "y": [2, 0, 1, 0, 1], "d": ["1980-10-20", "1980-10-21", "1980-10-22", "1980-10-23", "1980-10-24"]}

In [32]:
df = pd.DataFrame(data)

In [33]:
df

x1  x2  y           d
0   0  10  2  1980-10-20
1   1  11  0  1980-10-21
2   2  12  1  1980-10-22
3   3  13  0  1980-10-23
4   4  14  1  1980-10-24

In [34]:
df['Date'] = pd.to_datetime(df['d'])

In [35]:
df

x1  x2  y           d       Date
0   0  10  2  1980-10-20 1980-10-20
1   1  11  0  1980-10-21 1980-10-21
2   2  12  1  1980-10-22 1980-10-22
3   3  13  0  1980-10-23 1980-10-23
4   4  14  1  1980-10-24 1980-10-24

In [36]:
from bigdl.chronos.data import TSDataset

In [37]:
dataset = TSDataset.from_pandas(df, dt_col='Date', target_col='y', extra_feature_col=["x1", "x2"])

In [38]:
dataset.df

x1  x2  y           d       Date id
0   0  10  2  1980-10-20 1980-10-20  0
1   1  11  0  1980-10-21 1980-10-21  0
2   2  12  1  1980-10-22 1980-10-22  0
3   3  13  0  1980-10-23 1980-10-23  0
4   4  14  1  1980-10-24 1980-10-24  0

In [39]:
lookback, horizon = 1, 1

In [40]:
dataset.deduplicate().roll(lookback=lookback, horizon=horizon)

In [41]:
dataset.df

x1  x2  y           d       Date id
0   0  10  2  1980-10-20 1980-10-20  0
1   1  11  0  1980-10-21 1980-10-21  0
2   2  12  1  1980-10-22 1980-10-22  0
3   3  13  0  1980-10-23 1980-10-23  0
4   4  14  1  1980-10-24 1980-10-24  0

In [42]:
x, y = dataset.to_numpy()

In [43]:
x

array([[[ 2.,  0., 10.]],

       [[ 0.,  1., 11.]],

       [[ 1.,  2., 12.]],

       [[ 0.,  3., 13.]]], dtype=float32)

In [44]:
y

array([[[0.]],

       [[1.]],

       [[0.]],

       [[1.]]], dtype=float32)

In [45]:
lookback, horizon = 1, 2

In [46]:
dataset.deduplicate().roll(lookback=lookback, horizon=horizon)

In [47]:
x, y = dataset.to_numpy()

In [48]:
x

array([[[ 2.,  0., 10.]],

       [[ 0.,  1., 11.]],

       [[ 1.,  2., 12.]]], dtype=float32)

In [49]:
y

array([[[0.],
        [1.]],

       [[1.],
        [0.]],

       [[0.],
        [1.]]], dtype=float32)